
# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Docker

on:
  workflow_call:
    
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: Setup Docker Build
          uses: docker/setup-buildx-action@v3.4.0

        - name: Docker Login
          uses: docker/login-action@v3.2.0
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWD }}
            

          
          
 
     
